dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
networks:
  default: mainnet-fork
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    lending_pool_addresses_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349'
    dai_eth_price_feed: '0x22b58f1ebedfca50fef632bd73368b2fda96d541'
    # kovan non è aggiornato instant come la mainnet dalla quale
    # facciamo il fork quindi per cercare sto address vai su aave docs
    # e guarda nel json che ti danno loro quale è quello più recente
    dai_token: '0xff795577d9ac8bd7d90ee22b6c1703490b6512fd'
  mainnet-fork:
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    lending_pool_addresses_provider: '0xb53c1a33016b2dc2ff3653530bff1848a515c8c5'
    dai_eth_price_feed: '0x773616e4d11a78f511299002da57a0a94577f1f4'
    dai_token: '0x6b175474e89094c44da98b954eedeac495271d0f'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}